name: Codecov Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x  # Use the version your project requires

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --no-restore

      # Run tests and generate coverage report in Cobertura format
      - name: Run tests and generate coverage report
        run: |
          dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --results-directory ./TestResults

      # Install ReportGenerator
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      # Add .NET tools to PATH using environment file
      - name: Add .NET tools to PATH
        run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      # Convert coverage report to Codecov format
      - name: Convert coverage to Codecov format
        run: |
          reportgenerator "-reports:./TestResults/**/coverage.cobertura.xml" "-targetdir:./coverage" "-reporttypes:Cobertura"

      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/Cobertura.xml
          flags: unittests
